config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get     'login'   =>  :new
    post    'login'   =>  :create
    delete  'logout'  =>  :destroy
  end
  get 'sessions/create'
  get 'sessions/destroy'

  resources :users
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pragprop Books Online Store</title>
    <%= debug params %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
      I18n.defaultLocale = "<%= I18n.default_locale %>"
      I18n.locale = "<%= I18n.locale %>"
    </script>
    <%= javascript_pack_tag 'locale_switcher', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class='main'>
    <aside>
      <%= form_tag store_index_path, class: 'locale' do %>
        <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
        <%= submit_tag 'submit', id: "submit_locale_change" %>
      <% end %>
    </aside>

      <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
      <h1> <%= @page_title %> </h1>
    </header>

    <section class='content'>
      <nav class='side_nav'>
        <% if @cart %>
          <div id='cart' class='carts'>
            <%= render_if @cart && @cart.line_items.any?, @cart %>
          </div>
        <% end %>
        <ul>
          <li><a href='/'><%= t('.home') %></a></li>
          <li><a href='/questions'><%= t('.questions') %></a></li>
          <li><a href='/news'><%= t('.news') %></a></li>
          <li><a href='/contact'><%= t('.contact') %></a></li>
          <li><span class='nav_span_datetime'><%= Time.now.strftime('%d-%m-%Y %H:%M') %></span></li>
        </ul>

        <% if session[:user_id] %>
          <nav class='logged_in_nav'>
            <ul>
              <li><%= link_to 'Orders',   orders_path %></li>
              <li><%= link_to 'Products', products_path %></li>
              <li><%= link_to 'Users',    users_path %></li>
              <li><%= link_to 'Logout',   logout_path, method: :delete %></li>
            </ul>
          </nav>
        <% end %>

      </nav>

     <main class='<%= controller.controller_name %>'>
        <%= yield %>
      </main>
    </section>

  </body>
</html>